openapi: 3.0.2
info:
  title: Hello API
  version: 1.0.0
paths:
  /hello/{incoming-parameter}:
    get:
      parameters:
        - name: incoming-parameter
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                example1:
                  value:
                    message: "Hello ${incoming-parameter}"
